plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

loom {
	mods {
		"perspective" {
			sourceSet("main")
		}
	}
}

repositories {
	maven { url = "https://jitpack.io" }
	maven { url = "https://maven.terraformersmc.com/releases/" }
	mavenCentral()
	mavenLocal()
	exclusiveContent {
		forRepository {
			maven {
				name = "Modrinth"
				url = "https://api.modrinth.com/maven"
			}
		}
		filter {
			includeGroup "maven.modrinth"
		}
	}
	flatDir {
		dirs("libs")
	}
	maven { url = "https://maven.quiltmc.org/repository/release/" }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	modCompileOnly "com.terraformersmc:modmenu:${project.modmenu_version}"
	modImplementation("maven.modrinth:luminance:${project.luminance_version}")
	modImplementation("org.quiltmc:quilt-config:${project.quilt_config_version}")
	modImplementation(compileOnly("com.electronwill.night-config:core:${project.toml_version}"))
	modImplementation(compileOnly("com.electronwill.night-config:toml:${project.toml_version}"))
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}
	repositories {
	}
}