org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true

fabric.loom.multiProjectOptimisation=true

group=dev.dannytaylor
modrinth_slug=mclegoman-perspective
github_user=mclegoman
github_slug=perspective
modId=perspective
modName=Perspective
modDescription=
authors=dannytaylor
contributors=Nettakrim
license=LGPL-3.0-or-later
modVersion=2.0.0

compatibleVersions=1.21.8
compatibleLoaders=fabric