/*
    KeybindingUtils
    Author: MCLegoMan
    Github: N/A
    License: CC-BY 4.0
*/

package com.mclegoman.keybindingutils;

public class KUKeybindings {
    public static int NONE;
    public static int ESCAPE;
    public static int ONE;
    public static int TWO;
    public static int THREE;
    public static int FOUR;
    public static int FIVE;
    public static int SIX;
    public static int SEVEN;
    public static int EIGHT;
    public static int NINE;
    public static int ZERO;
    public static int MINUS;
    public static int EQUALS;
    public static int BACK;
    public static int TAB;
    public static int Q;
    public static int W;
    public static int E;
    public static int R;
    public static int T;
    public static int Y;
    public static int U;
    public static int I;
    public static int O;
    public static int P;
    public static int LBRACKET;
    public static int RBRACKET;
    public static int RETURN;
    public static int LCONTROL;
    public static int A;
    public static int S;
    public static int D;
    public static int F;
    public static int G;
    public static int H;
    public static int J;
    public static int K;
    public static int L;
    public static int SEMICOLON;
    public static int APOSTROPHE;
    public static int GRAVE;
    public static int LSHIFT;
    public static int BACKSLASH;
    public static int Z;
    public static int X;
    public static int C;
    public static int V;
    public static int B;
    public static int N;
    public static int M;
    public static int COMMA;
    public static int PERIOD;
    public static int SLASH;
    public static int RSHIFT;
    public static int MULTIPLY;
    public static int LMENU;
    public static int SPACE;
    public static int CAPITAL;
    public static int F1;
    public static int F2;
    public static int F3;
    public static int F4;
    public static int F5;
    public static int F6;
    public static int F7;
    public static int F8;
    public static int F9;
    public static int F10;
    public static int NUMLOCK;
    public static int SCROLL;
    public static int NUMPAD7;
    public static int NUMPAD8;
    public static int NUMPAD9;
    public static int SUBTRACT;
    public static int NUMPAD4;
    public static int NUMPAD5;
    public static int NUMPAD6;
    public static int ADD;
    public static int NUMPAD1;
    public static int NUMPAD2;
    public static int NUMPAD3;
    public static int NUMPAD0;
    public static int DECIMAL;
    public static int F11;
    public static int F12;
    public static int F13;
    public static int F14;
    public static int F15;
    public static int KANA;
    public static int CONVERT;
    public static int NOCONVERT;
    public static int YEN;
    public static int NUMPADPADEQUALS;
    public static int CIRCUMFLEX;
    public static int AT;
    public static int COLON;
    public static int UNDERLINE;
    public static int KANJI;
    public static int STOP;
    public static int AX;
    public static int UNLABLED;
    public static int NUMPADPADENTER;
    public static int RCONTROL;
    public static int NUMPADPADCOMMA;
    public static int DIVIDE;
    public static int SYSRQ;
    public static int RMENU;
    public static int PAUSE;
    public static int HOME;
    public static int UP;
    public static int PRIOR;
    public static int LEFT;
    public static int RIGHT;
    public static int END;
    public static int DOWN;
    public static int NEXT;
    public static int INSERT;
    public static int DELETE;
    public static int LMETA;
    public static int LWIN;
    public static int RMETA;
    public static int RWIN;
    public static int APPS;
    public static int POWER;
    public static int SLEEP;
    static {
        NONE = 0;
        ESCAPE = 1;
        ONE = 2;
        TWO = 3;
        THREE = 4;
        FOUR = 5;
        FIVE = 6;
        SIX = 7;
        SEVEN = 8;
        EIGHT = 9;
        NINE = 10;
        ZERO = 11;
        MINUS = 12;
        EQUALS = 13;
        BACK = 14;
        TAB = 15;
        Q = 16;
        W = 17;
        E = 18;
        R = 19;
        T = 20;
        Y = 21;
        U = 22;
        I = 23;
        O = 24;
        P = 25;
        LBRACKET = 26;
        RBRACKET = 27;
        RETURN = 28;
        LCONTROL = 29;
        A = 30;
        S = 31;
        D = 32;
        F = 33;
        G = 34;
        H = 35;
        J = 36;
        K = 37;
        L = 38;
        SEMICOLON = 39;
        APOSTROPHE = 40;
        GRAVE = 41;
        LSHIFT = 42;
        BACKSLASH = 43;
        Z = 44;
        X = 45;
        C = 46;
        V = 47;
        B = 48;
        N = 49;
        M = 50;
        COMMA = 51;
        PERIOD = 52;
        SLASH = 53;
        RSHIFT = 54;
        MULTIPLY = 55;
        LMENU = 56;
        SPACE = 57;
        CAPITAL = 58;
        F1 = 59;
        F2 = 60;
        F3 = 61;
        F4 = 62;
        F5 = 63;
        F6 = 64;
        F7 = 65;
        F8 = 66;
        F9 = 67;
        F10 = 68;
        NUMLOCK = 69;
        SCROLL = 70;
        NUMPAD7 = 71;
        NUMPAD8 = 72;
        NUMPAD9 = 73;
        SUBTRACT = 74;
        NUMPAD4 = 75;
        NUMPAD5 = 76;
        NUMPAD6 = 77;
        ADD = 78;
        NUMPAD1 = 79;
        NUMPAD2 = 80;
        NUMPAD3 = 81;
        NUMPAD0 = 82;
        DECIMAL = 83;
        F11 = 87;
        F12 = 88;
        F13 = 100;
        F14 = 101;
        F15 = 102;
        KANA = 112;
        CONVERT = 121;
        NOCONVERT = 123;
        YEN = 125;
        NUMPADPADEQUALS = 141;
        CIRCUMFLEX = 144;
        AT = 145;
        COLON = 146;
        UNDERLINE = 147;
        KANJI = 148;
        STOP = 149;
        AX = 150;
        UNLABLED = 151;
        NUMPADPADENTER = 156;
        RCONTROL = 157;
        NUMPADPADCOMMA = 179;
        DIVIDE = 181;
        SYSRQ = 183;
        RMENU = 184;
        PAUSE = 197;
        HOME = 199;
        UP = 200;
        PRIOR = 201;
        LEFT = 203;
        RIGHT = 205;
        END = 207;
        DOWN = 208;
        NEXT = 209;
        INSERT = 210;
        DELETE = 211;
        LMETA = 219;
        LWIN = 219;
        RMETA = 220;
        RWIN = 220;
        APPS = 221;
        POWER = 222;
        SLEEP = 223;
    }
}
