import shutil
print("Make sure the folder where this script is located contains your texture file as 'cat.png'!")
name = input("Enter Name: ").lower()
shutil.copy('./cat.png', './' + name + '_tabby.png')
shutil.copy('./cat.png', './' + name + '_black.png')
shutil.copy('./cat.png', './' + name + '_red.png')
shutil.copy('./cat.png', './' + name + '_siamese.png')
shutil.copy('./cat.png', './' + name + '_british_shorthair.png')
shutil.copy('./cat.png', './' + name + '_calico.png')
shutil.copy('./cat.png', './' + name + '_persian.png')
shutil.copy('./cat.png', './' + name + '_ragdoll.png')
shutil.copy('./cat.png', './' + name + '_white.png')
shutil.copy('./cat.png', './' + name + '_jellie.png')
shutil.copy('./cat.png', './' + name + '_all_black.png')