org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true

fabric.loom.multiProjectOptimisation=true

group=dev.dannytaylor
user=mclegoman
modrinth_slug=perspective
github_slug=perspective
modId=perspective_config
modName=Parameter
modDescription=Centralizes and manages all of Perspective's settings in one place.
authors=dannytaylor
contributors=
license=LGPL-3.0-or-later
modVersion=1.0.0
compatibleVersions=1.21.8