title: Perspective
description: Perspective
remote_theme: just-the-docs/just-the-docs

url: https://mclegoman.github.io/perspective

nav_external_links:
  - title: Curseforge
    url: https://www.curseforge.com/minecraft/mc-mods/perspective
  - title: Github
    url: https://github.com/MCLegoMan/Perspective
  - title: Report an Issue
    url: https://github.com/MCLegoMan/Perspective/issues/new/choose
  - title: Donate
    url: https://ko-fi.com/mclegoman

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: false

enable_copy_code_button: true

callouts:
  warning:
    title: "WARNING"
    color: red
  important:
    title: "IMPORTANT"
    color: yellow
  requires:
    title: "REQUIRES"
    color: blue
  untitled:
    color: blue
  development:
    title: "DEVELOPMENT"
    color: yellow
  release:
    title: "RELEASE"
    color: green
  add_to_showcase:
    title: "WANT TO ADD A VIDEO TO THIS LIST?"
    color: red

nav_sort: case_sensitive

back_to_top: true
back_to_top_text: "Back to top"

color_scheme: dark
